services:
  production:
    container_name: "amusfq.dev"
    restart: unless-stopped 
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    env_file: 
      - ./.env